import { describe, expect, it } from "vitest";
import {
  createYouTubeCaptionChapters,
  extractKoreanYouTubeCaptionTrack,
  extractKoreanYouTubeCaptionTrackFromPlayerResponse,
  parseYouTubeCaptionJson3,
  youtubeVideoIdFromSourceName,
} from "./youtubeCaptionTrack";

describe("youtubeCaptionTrack", () => {
  it("extracts the Korean caption URL from a bounded player response", () => {
    const player = {
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            { languageCode: "en", baseUrl: "https://www.youtube.com/api/timedtext?lang=en" },
            { languageCode: "ko", kind: "asr", baseUrl: "https://www.youtube.com/api/timedtext?lang=ko" },
          ],
        },
      },
    };
    const track = extractKoreanYouTubeCaptionTrack(
      `<script>var ytInitialPlayerResponse = ${JSON.stringify(player)};</script>`,
      "KzAW3yow80Q",
    );
    expect(track).toMatchObject({
      videoId: "KzAW3yow80Q",
      languageCode: "ko",
      isAutoGenerated: true,
    });
    expect(new URL(track!.baseUrl).searchParams.get("fmt")).toBe("json3");
    expect(
      extractKoreanYouTubeCaptionTrackFromPlayerResponse(player, "KzAW3yow80Q"),
    ).toEqual(track);
  });

  it("normalizes timestamped JSON3 events without inventing text", () => {
    const track = {
      videoId: "KzAW3yow80Q",
      languageCode: "ko",
      isAutoGenerated: true,
      baseUrl: "https://www.youtube.com/api/timedtext?fmt=json3",
    };
    expect(parseYouTubeCaptionJson3({
      events: [
        { tStartMs: 1_000, dDurationMs: 2_000, segs: [{ utf8: "제가 " }, { utf8: "틀렸어요" }] },
      ],
    }, track)).toEqual({
      videoId: "KzAW3yow80Q",
      languageCode: "ko",
      isAutoGenerated: true,
      events: [{ startMs: 1_000, durationMs: 2_000, text: "제가 틀렸어요" }],
    });
  });

  it("detects a bracketed video id and builds a bounded complete transcript map", () => {
    expect(
      youtubeVideoIdFromSourceName("2026 07 17 - 음식 토크[KzAW3yow80Q].mp4"),
    ).toBe("KzAW3yow80Q");
    expect(youtubeVideoIdFromSourceName("내 영상.mp4")).toBeNull();
    const chapters = createYouTubeCaptionChapters(
      {
        videoId: "KzAW3yow80Q",
        languageCode: "ko",
        isAutoGenerated: true,
        events: [
          { startMs: 1_000, durationMs: 2_000, text: "방송을 시작합니다." },
          { startMs: 121_000, durationMs: 2_000, text: "제가 잘못했습니다." },
        ],
      },
      240_000,
    );
    expect(chapters).toHaveLength(2);
    expect(chapters[0]?.summaryKo).toContain("방송을 시작");
    expect(chapters[1]?.summaryKo).toContain("잘못했습니다");
    expect(chapters.every((chapter) => chapter.evidenceMode === "complete-transcript")).toBe(true);
  });
});
