import {
  MAX_BROADCAST_CONTEXT_CHAPTERS,
  MAX_BROADCAST_CONTEXT_SUMMARY_LENGTH,
  type BroadcastContextChapterInput,
} from "./broadcastContextProtocol";

export const YOUTUBE_VIDEO_ID_PATTERN = /^[A-Za-z0-9_-]{11}$/u;
export const MAX_YOUTUBE_CAPTION_EVENTS = 120_000;
export const MAX_YOUTUBE_CAPTION_EVENT_TEXT_LENGTH = 500;
export const YOUTUBE_CAPTION_MODEL_REVISION =
  "youtube-korean-caption-json3-android-player-2026-07-22" as const;
const MAX_CAPTION_TIME_MS = 12 * 60 * 60_000;

export interface YouTubeCaptionTrackReference {
  readonly videoId: string;
  readonly languageCode: string;
  readonly isAutoGenerated: boolean;
  readonly baseUrl: string;
}

export interface YouTubeCaptionEvent {
  readonly startMs: number;
  readonly durationMs: number;
  readonly text: string;
}

export interface YouTubeCaptionTrackResult {
  readonly videoId: string;
  readonly languageCode: string;
  readonly isAutoGenerated: boolean;
  readonly events: readonly YouTubeCaptionEvent[];
}

export function youtubeVideoIdFromSourceName(sourceName: string): string | null {
  if (typeof sourceName !== "string") return null;
  const match = /\[([A-Za-z0-9_-]{11})\](?:\.[^.]+)?$/u.exec(sourceName.trim());
  return match?.[1] ?? null;
}

function representativeCaptionText(
  values: readonly string[],
  maximumLength: number,
): string {
  const normalized = values
    .join(" ")
    .replace(/[\p{Cc}\p{Cf}]/gu, " ")
    .replace(/\s+/gu, " ")
    .trim();
  const points = Array.from(normalized || "[대사 없음]");
  if (points.length <= maximumLength) return points.join("").trim();
  const separator = " … ";
  const sliceCount = 4;
  const sliceLength = Math.floor(
    (maximumLength - Array.from(separator).length * (sliceCount - 1)) /
      sliceCount,
  );
  const maximumStart = points.length - sliceLength;
  return Array.from({ length: sliceCount }, (_, index) => {
    const start = Math.round((maximumStart * index) / (sliceCount - 1));
    return points.slice(start, start + sliceLength).join("");
  })
    .join(separator)
    .trim();
}

/** Builds a complete, bounded context map directly from a matching video track. */
export function createYouTubeCaptionChapters(
  track: YouTubeCaptionTrackResult,
  sourceDurationMs: number,
): readonly BroadcastContextChapterInput[] {
  if (
    !Number.isSafeInteger(sourceDurationMs) ||
    sourceDurationMs <= 0 ||
    sourceDurationMs > MAX_CAPTION_TIME_MS ||
    track.events.length === 0
  ) {
    return [];
  }
  const minimumChapterMs = 120_000;
  const chapterDurationMs = Math.max(
    minimumChapterMs,
    Math.ceil(sourceDurationMs / MAX_BROADCAST_CONTEXT_CHAPTERS / 1_000) * 1_000,
  );
  const chapters: BroadcastContextChapterInput[] = [];
  for (let startMs = 0; startMs < sourceDurationMs; startMs += chapterDurationMs) {
    const endMs = Math.min(sourceDurationMs, startMs + chapterDurationMs);
    chapters.push({
      chapterId: `youtube-${String(chapters.length + 1).padStart(3, "0")}`,
      startMs,
      endMs,
      evidenceMode: "complete-transcript",
      evidenceCoverageRatio: 1,
      summaryKo: representativeCaptionText(
        track.events
          .filter(
            (event) =>
              event.startMs < endMs &&
              event.startMs + event.durationMs >= startMs,
          )
          .map((event) => event.text),
        MAX_BROADCAST_CONTEXT_SUMMARY_LENGTH,
      ),
    });
  }
  return chapters;
}

export function extractKoreanYouTubeCaptionTrackFromPlayerResponse(
  response: unknown,
  videoId: string,
): YouTubeCaptionTrackReference | null {
  if (!YOUTUBE_VIDEO_ID_PATTERN.test(videoId) || !isRecord(response) || !isRecord(response.captions)) {
    return null;
  }
  const renderer = response.captions.playerCaptionsTracklistRenderer;
  if (!isRecord(renderer) || !Array.isArray(renderer.captionTracks)) return null;
  const tracks = renderer.captionTracks
    .filter(isRecord)
    .filter(
      (track) =>
        typeof track.languageCode === "string" &&
        (track.languageCode === "ko" || track.languageCode.startsWith("ko-")) &&
        typeof track.baseUrl === "string",
    )
    .sort((left, right) => {
      const leftAsr = left.kind === "asr" ? 1 : 0;
      const rightAsr = right.kind === "asr" ? 1 : 0;
      return leftAsr - rightAsr;
    });
  const selected = tracks[0];
  if (selected === undefined) return null;
  let url: URL;
  try {
    url = new URL(selected.baseUrl as string);
  } catch {
    return null;
  }
  if (
    url.protocol !== "https:" ||
    (url.hostname !== "www.youtube.com" && url.hostname !== "youtube.com") ||
    url.pathname !== "/api/timedtext" ||
    url.username !== "" ||
    url.password !== ""
  ) {
    return null;
  }
  url.searchParams.set("fmt", "json3");
  return {
    videoId,
    languageCode: selected.languageCode as string,
    isAutoGenerated: selected.kind === "asr",
    baseUrl: url.toString(),
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function balancedJsonObject(source: string, startIndex: number): string | null {
  const objectStart = source.indexOf("{", startIndex);
  if (objectStart < 0) return null;
  let depth = 0;
  let quoted = false;
  let escaped = false;
  for (let index = objectStart; index < source.length; index += 1) {
    const character = source[index]!;
    if (quoted) {
      if (escaped) escaped = false;
      else if (character === "\\") escaped = true;
      else if (character === '"') quoted = false;
      continue;
    }
    if (character === '"') quoted = true;
    else if (character === "{") depth += 1;
    else if (character === "}") {
      depth -= 1;
      if (depth === 0) return source.slice(objectStart, index + 1);
    }
  }
  return null;
}

export function extractKoreanYouTubeCaptionTrack(
  html: string,
  videoId: string,
): YouTubeCaptionTrackReference | null {
  if (typeof html !== "string" || !YOUTUBE_VIDEO_ID_PATTERN.test(videoId)) return null;
  const markers = ["ytInitialPlayerResponse =", '"ytInitialPlayerResponse":'];
  let response: unknown = null;
  for (const marker of markers) {
    const markerIndex = html.indexOf(marker);
    if (markerIndex < 0) continue;
    const json = balancedJsonObject(html, markerIndex + marker.length);
    if (json === null) continue;
    try {
      response = JSON.parse(json);
      break;
    } catch {
      // Try the next known embedding form.
    }
  }
  return extractKoreanYouTubeCaptionTrackFromPlayerResponse(response, videoId);
}

function normalizedCaptionText(value: unknown): string | null {
  if (!Array.isArray(value)) return null;
  const text = value
    .map((segment) => isRecord(segment) && typeof segment.utf8 === "string" ? segment.utf8 : "")
    .join("")
    .normalize("NFKC")
    .replace(/[\p{Cc}\p{Cf}]/gu, " ")
    .replace(/\s+/gu, " ")
    .trim();
  if (text.length === 0) return null;
  return Array.from(text).slice(0, MAX_YOUTUBE_CAPTION_EVENT_TEXT_LENGTH).join("").trim();
}

export function parseYouTubeCaptionJson3(
  value: unknown,
  track: YouTubeCaptionTrackReference,
): YouTubeCaptionTrackResult | null {
  if (!isRecord(value) || !Array.isArray(value.events)) return null;
  const events: YouTubeCaptionEvent[] = [];
  let previousKey = "";
  for (const raw of value.events) {
    if (events.length >= MAX_YOUTUBE_CAPTION_EVENTS || !isRecord(raw)) break;
    const startMs = raw.tStartMs;
    const durationMs = raw.dDurationMs;
    const text = normalizedCaptionText(raw.segs);
    if (
      !Number.isSafeInteger(startMs) ||
      (startMs as number) < 0 ||
      (startMs as number) > MAX_CAPTION_TIME_MS ||
      !Number.isSafeInteger(durationMs) ||
      (durationMs as number) < 0 ||
      text === null
    ) {
      continue;
    }
    const normalizedStartMs = startMs as number;
    const normalizedDurationMs = durationMs as number;
    const key = `${normalizedStartMs}:${text}`;
    if (key === previousKey) continue;
    previousKey = key;
    events.push({ startMs: normalizedStartMs, durationMs: normalizedDurationMs, text });
  }
  if (events.length === 0) return null;
  return {
    videoId: track.videoId,
    languageCode: track.languageCode,
    isAutoGenerated: track.isAutoGenerated,
    events,
  };
}
