import {
  MAX_YOUTUBE_CAPTION_EVENTS,
  MAX_YOUTUBE_CAPTION_EVENT_TEXT_LENGTH,
  YOUTUBE_VIDEO_ID_PATTERN,
  type YouTubeCaptionEvent,
  type YouTubeCaptionTrackResult,
} from "./youtubeCaptionTrack";

export const YOUTUBE_CAPTION_PROXY_ENDPOINT =
  "https://rettohighlight-gemini.11qaws.workers.dev/v1/youtube-captions" as const;
const MAX_YOUTUBE_CAPTION_RESPONSE_BYTES = 8 * 1024 * 1024;

type FetchImplementation = (
  input: RequestInfo | URL,
  init?: RequestInit,
) => Promise<Response>;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function parseYouTubeCaptionProxyResult(
  value: unknown,
  expectedVideoId: string,
): YouTubeCaptionTrackResult | null {
  if (
    !YOUTUBE_VIDEO_ID_PATTERN.test(expectedVideoId) ||
    !isRecord(value) ||
    value.videoId !== expectedVideoId ||
    typeof value.languageCode !== "string" ||
    !(value.languageCode === "ko" || value.languageCode.startsWith("ko-")) ||
    typeof value.isAutoGenerated !== "boolean" ||
    !Array.isArray(value.events) ||
    value.events.length === 0 ||
    value.events.length > MAX_YOUTUBE_CAPTION_EVENTS
  ) {
    return null;
  }
  const events: YouTubeCaptionEvent[] = [];
  let previousStartMs = -1;
  for (const item of value.events) {
    if (
      !isRecord(item) ||
      !Number.isSafeInteger(item.startMs) ||
      !Number.isSafeInteger(item.durationMs) ||
      (item.startMs as number) < previousStartMs ||
      (item.startMs as number) < 0 ||
      (item.durationMs as number) < 0 ||
      typeof item.text !== "string" ||
      item.text.trim() !== item.text ||
      item.text.length === 0 ||
      Array.from(item.text).length > MAX_YOUTUBE_CAPTION_EVENT_TEXT_LENGTH ||
      /[\p{Cc}\p{Cf}]/u.test(item.text)
    ) {
      return null;
    }
    previousStartMs = item.startMs as number;
    events.push({
      startMs: item.startMs as number,
      durationMs: item.durationMs as number,
      text: item.text,
    });
  }
  return {
    videoId: expectedVideoId,
    languageCode: value.languageCode,
    isAutoGenerated: value.isAutoGenerated,
    events,
  };
}

export async function requestYouTubeCaptionTrack(
  videoId: string,
  options: {
    readonly signal?: AbortSignal;
    readonly fetchImplementation?: FetchImplementation;
  } = {},
): Promise<YouTubeCaptionTrackResult> {
  if (!YOUTUBE_VIDEO_ID_PATTERN.test(videoId)) {
    throw new RangeError("Invalid YouTube video ID.");
  }
  const response = await (options.fetchImplementation ?? fetch)(
    `${YOUTUBE_CAPTION_PROXY_ENDPOINT}?v=${encodeURIComponent(videoId)}`,
    {
      method: "GET",
      credentials: "omit",
      cache: "no-store",
      referrerPolicy: "no-referrer",
      ...(options.signal === undefined ? {} : { signal: options.signal }),
    },
  );
  if (!response.ok) {
    await response.body?.cancel().catch(() => undefined);
    throw new Error("YouTube captions are unavailable.");
  }
  const declaredLength = response.headers.get("Content-Length");
  if (
    declaredLength !== null &&
    (!/^\d+$/u.test(declaredLength) ||
      Number(declaredLength) > MAX_YOUTUBE_CAPTION_RESPONSE_BYTES)
  ) {
    await response.body?.cancel().catch(() => undefined);
    throw new Error("YouTube caption response is too large.");
  }
  const text = await response.text();
  if (new TextEncoder().encode(text).byteLength > MAX_YOUTUBE_CAPTION_RESPONSE_BYTES) {
    throw new Error("YouTube caption response is too large.");
  }
  let payload: unknown;
  try {
    payload = JSON.parse(text) as unknown;
  } catch {
    throw new Error("YouTube caption response is invalid.");
  }
  const result = parseYouTubeCaptionProxyResult(payload, videoId);
  if (result === null) {
    throw new Error("YouTube caption response is invalid.");
  }
  return result;
}
