import { describe, expect, it, vi } from "vitest";

import {
  YOUTUBE_CAPTION_PROXY_ENDPOINT,
  parseYouTubeCaptionProxyResult,
  requestYouTubeCaptionTrack,
} from "./youtubeCaptionClient";

const payload = {
  videoId: "KzAW3yow80Q",
  languageCode: "ko",
  isAutoGenerated: true,
  events: [{ startMs: 1_000, durationMs: 2_000, text: "제가 틀렸어요" }],
};

describe("youtubeCaptionClient", () => {
  it("validates a source-fenced Korean caption response", () => {
    expect(parseYouTubeCaptionProxyResult(payload, "KzAW3yow80Q")).toEqual(payload);
    expect(parseYouTubeCaptionProxyResult(payload, "EZfCGS5ms_Q")).toBeNull();
  });

  it("requests the fixed proxy endpoint without credentials", async () => {
    const fetchImplementation = vi.fn(() =>
      Promise.resolve(new Response(JSON.stringify(payload), { status: 200 })),
    );
    await expect(
      requestYouTubeCaptionTrack("KzAW3yow80Q", { fetchImplementation }),
    ).resolves.toEqual(payload);
    expect(fetchImplementation).toHaveBeenCalledWith(
      `${YOUTUBE_CAPTION_PROXY_ENDPOINT}?v=KzAW3yow80Q`,
      expect.objectContaining({ method: "GET", credentials: "omit" }),
    );
  });
});
